ClusterName=drone-fixture
SlurmctldHost=drone-slurm
SlurmUser=slurm
StateSaveLocation=/var/spool/slurmctld
SlurmdSpoolDir=/var/spool/slurmd
SlurmctldPidFile=/run/slurmctld.pid
SlurmdPidFile=/run/slurmd.pid
AuthType=auth/munge
CryptoType=crypto/munge
MpiDefault=none
ProctrackType=proctrack/pgid
ReturnToService=2
SlurmctldPort=6817
SlurmdPort=6818
SwitchType=switch/none
TaskPlugin=task/none
SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_CPU
NodeName=drone-slurm CPUs=10 RealMemory=2048 State=UNKNOWN
PartitionName=debug Nodes=drone-slurm Default=YES MaxTime=INFINITE State=UP
