import { lstat, mkdir, realpath, writeFile } from "node:fs/promises";
import { isAbsolute, join, relative, resolve, sep } from "node:path";
import type { CommandResult, CommandRunner, CompiledWorkflow, ComputeWorkflowSpec } from "./types";
import { assertValidWorkflowSpec, referenceKey, type WorkflowModuleCatalog } from "./workflow";

const safeProcess = /^[A-Za-z_][A-Za-z0-9_]*$/;
const safePath = /^[A-Za-z0-9_./-]+$/;

function quoteGroovy(value: string): string {
	return `'${value.replaceAll("'", "\\'")}'`;
}

function formatParam(value: string | number | boolean): string {
	if (typeof value === "string") return quoteGroovy(value);
	return String(value);
}

function sourceExpression(reference: string | { input: string } | { step: string; output: string }): string {
	if (typeof reference !== "string") {
		if ("input" in reference) return `${reference.input}_ch`;
		return `${reference.step}_${reference.output}_ch`;
	}
	if (reference.startsWith("input:")) return `${reference.slice(6)}_ch`;
	const match = /^step:([a-z][a-z0-9_-]*)\.([a-z][a-z0-9_-]*)$/.exec(reference);
	return match?.[1] && match[2] ? `${match[1]}_${match[2]}_ch` : "INVALID_REFERENCE";
}

function processAlias(id: string): string {
	return id.replaceAll("-", "_");
}

/** Compile a validated graph into a small, data-only DSL2 entry point. */
export function compileWorkflow(spec: ComputeWorkflowSpec, catalog: WorkflowModuleCatalog): CompiledWorkflow {
	const hash = assertValidWorkflowSpec(spec, catalog);
	const invocations = spec.steps.flatMap((step) => {
		const module = catalog.get(step.module);
		return module ? [{ step, module }] : [];
	});
	const uniqueModules = [...new Map(invocations.map(({ module }) => [module.id, module])).values()];
	const includes = invocations.map(({ step, module }) => {
		if (!safeProcess.test(module.process)) throw new Error(`Unsafe process name for module ${module.id}`);
		if (!safePath.test(module.path) || module.path.startsWith("/") || module.path.includes(".."))
			throw new Error(`Unsafe module path for ${module.id}`);
		return `include { ${module.process} as ${processAlias(step.id)}_${module.process} } from '${module.path}'`;
	});
	const lines = ["nextflow.enable.dsl=2", ...includes, "", "workflow {\n"];
	for (const input of spec.inputs) {
		const paramName = input.param ?? input.name;
		if (!safeProcess.test(paramName)) throw new Error(`Unsafe input parameter ${paramName}`);
		lines.push(`    ${input.name}_ch = Channel.fromPath(params.${paramName}, checkIfExists: true)`);
	}
	for (const step of spec.steps) {
		const module = catalog.get(step.module);
		if (!module) continue;
		const args = module.inputs.flatMap((port) => {
			const reference = step.inputs[port.name];
			return reference === undefined ? [] : [sourceExpression(reference)];
		});
		const params = Object.entries(step.params ?? {}).map(([key, value]) => {
			if (!safeProcess.test(key)) throw new Error(`Unsafe module parameter ${key}`);
			return `${key}: ${formatParam(value)}`;
		});
		const allArgs = [...args, ...params];
		const invocation = `${processAlias(step.id)}_${module.process}`;
		lines.push(`    ${invocation}(${allArgs.join(", ")})`);
		for (const output of module.outputs)
			lines.push(`    ${processAlias(step.id)}_${output.name}_ch = ${invocation}.out.${output.name}`);
	}
	lines.push("}\n");

	const parameters = Object.entries(spec.parameters ?? {}).map(([key, value]) => {
		if (!safeProcess.test(key)) throw new Error(`Unsafe workflow parameter ${key}`);
		return `${key} = ${formatParam(value)}`;
	});
	const nextflowConfig = [
		"// Generated by @drone/compute. Do not edit; regenerate from the approved ComputeWorkflowSpec.",
		"nextflow.enable.dsl=2",
		"params {",
		...parameters.map((line) => `    ${line}`),
		"}",
		"process {",
		"    errorStrategy = 'terminate'",
		"}",
		"",
	].join("\n");
	return {
		mainNf: `${lines.join("\n")}\n`,
		nextflowConfig,
		workflowSpecSha256: hash,
		moduleCommits: Object.fromEntries(uniqueModules.map((module) => [module.id, module.commit])),
		containerDigests: Object.fromEntries(
			uniqueModules
				.filter((module) => module.containerDigest)
				.map((module) => [module.id, module.containerDigest as string]),
		),
	};
}

export interface NextflowPreviewResult {
	ok: boolean;
	command: readonly string[];
	result: CommandResult;
}

/** Run the local, injected Nextflow adapter. No shell command is ever constructed. */
export async function previewWorkflow(
	_artifact: CompiledWorkflow,
	runner: CommandRunner,
	options: { cwd: string; nextflow?: string; profile?: string } = { cwd: "." },
): Promise<NextflowPreviewResult> {
	const executable = options.nextflow ?? "nextflow";
	const args = ["run", "main.nf", "-preview", "-c", "nextflow.config"];
	if (options.profile) args.push("-profile", options.profile);
	const result = await runner.run(executable, args, { cwd: options.cwd });
	return { ok: result.exitCode === 0, command: [executable, ...args], result };
}

export async function validateCompiledWorkflow(
	spec: ComputeWorkflowSpec,
	catalog: WorkflowModuleCatalog,
	runner: CommandRunner,
	options: { cwd: string; nextflow?: string; profile?: string },
): Promise<NextflowPreviewResult & { artifact: CompiledWorkflow }> {
	const artifact = compileWorkflow(spec, catalog);
	const preview = await previewWorkflow(artifact, runner, options);
	return { ...preview, artifact };
}

export async function writeCompiledWorkflow(
	artifact: CompiledWorkflow,
	outputDir: string,
	approvedRoot: string,
): Promise<{ directory: string; files: readonly string[] }> {
	const root = await realpath(approvedRoot);
	const directory = resolve(root, outputDir);
	const relativePath = relative(root, directory);
	if (relativePath.startsWith("..") || isAbsolute(relativePath))
		throw new Error("Compiled workflow directory is outside the approved root");
	let cursor = root;
	for (const part of relativePath.split(sep).filter(Boolean)) {
		cursor = join(cursor, part);
		try {
			if ((await lstat(cursor)).isSymbolicLink())
				throw new Error("Compiled workflow directory cannot contain a symlink");
		} catch (error) {
			if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
			break;
		}
	}
	await mkdir(directory, { recursive: true });
	const main = resolve(directory, "main.nf");
	const config = resolve(directory, "nextflow.config");
	for (const file of [main, config]) {
		try {
			if ((await lstat(file)).isSymbolicLink())
				throw new Error("Compiled workflow files cannot be symbolic links");
		} catch (error) {
			if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
		}
	}
	await writeFile(main, artifact.mainNf, "utf8");
	await writeFile(config, artifact.nextflowConfig, "utf8");
	return { directory, files: [main, config] };
}

/** Small fake runner for hermetic tests and CI without a Nextflow installation. */
export class FakeCommandRunner implements CommandRunner {
	readonly calls: Array<{ command: string; args: readonly string[]; cwd?: string }> = [];
	constructor(private readonly response: CommandResult = { exitCode: 0, stdout: "" }) {}
	async run(command: string, args: readonly string[], options?: { cwd?: string }): Promise<CommandResult> {
		this.calls.push({ command, args: [...args], cwd: options?.cwd });
		return this.response;
	}
}

export { referenceKey };
