import { useI18nStore } from "../../i18n";
export const knowledgeZh = {
 "specialists": "知识库专用子智能体",
 "specialistMode": "自动调度模式",
 "specialistAuto": "按阶段自动调用",
 "specialistManual": "仅明确委派",
 "specialistOff": "关闭",
 "specialistCost": "子智能体是独立模型请求，可能产生费用。默认沿用主模型；可在模型设置中单独指定。只传当前任务与必要来源，不传主会话历史。",
 "specialistDenied": "当前 Vault 禁止子智能体访问；调度关闭，不能用此开关提权。",
 "specialistPermissions": "角色、职责与最小权限",
 "specialistLimits": "每轮最多 4 次，知识子智能体全应用最多并发 2 个；单个最长 120 秒。无 shell、网络抓取、递归委派、正式 Wiki 写入或批准权限。",
 "specialistModels": "配置子智能体模型",
 "specialist_navigator": "知识导航员",
 "specialist_navigator_hint": "知识请求开始时读导航、找相关 Wiki 与证据；返回少量入口。",
 "specialist_evidence": "证据整理员",
 "specialist_evidence_hint": "多来源比较时核对范围、版本与冲突；不认证科学正确性。",
 "specialist_wiki": "Wiki 修订员",
 "specialist_wiki_hint": "摘要保存后起草修订；宿主暂存候选，仍需你审核。",
 "specialist_explainer": "Show Me 讲解员",
 "specialist_explainer_hint": "基于指定来源和已加载的 skill 生成讲解；宿主归档，不执行软件测试。",
 "specialistRuns": "专用子智能体运行",
 "specialistUsage": "输入 / 输出 tokens",
 "specialistUnverified": "子智能体摘要是待核验交接，不是主会话已读证据或最终结论。",
 "worker_queued": "排队",
 "worker_running": "运行中",
 "worker_completed": "已交接",
 "worker_failed": "失败",
 "worker_cancelled": "已取消",
 "worker_skipped": "已跳过",

 linkPreviewOnly:"原笔记未改写；本地来源链接按相同项目的现存结果文件解析：",
 emptyPreview:"目录为空或尚未选择路径；下方仍可预览将使用的结构和模板。",
 sampleContent:"笔记模板正文（只读）",
 setupComplete:"初始化完成",
 findings:"具体检索结果",
 candidateHint:"检索片段，不等于模型已阅读或科学结论已验证。",
 outputs:"本轮产物与待办",
 noFindings:"本轮尚无匹配条目。索引中的资料与整理后的 Wiki 是不同层次。",
  "title": "知识库",
  "subtitle": "全应用共享 · 项目背景独立",
  "overview": "总览与配置",
  "reviews": "Wiki 审核",
  "maintenance": "索引与维护",
  "refresh": "刷新状态",
  "loading": "正在读取本地状态…",
  "failed": "操作未完成",
  "retry": "重试",
  "close": "关闭",
  "notBound": "尚未绑定共享知识库",
  "notBoundHint": "创建或选择一次，所有项目和新会话共同使用。代码与结果目录仍属于各自项目。",
  "disabled": "此运行环境尚未启用应用级知识库。请使用新的桌面构建。",
  "vault": "当前 Vault",
  "scope": "作用范围",
  "scopeValue": "整个 Percho",
  "project": "当前知识项目",
  "noProject": "未选择项目；仅显示共享状态",
  "profile": "知识结构",
  "deposit": "沉淀策略",
  "subagents": "子智能体访问",
  "index": "本地索引",
  "notes": "已索引笔记",
  "pending": "待处理文件",
  "jobs": "维护任务",
  "lastChecked": "最近目录核对",
  "unknown": "尚未完成",
  "watching": "文件监听正常",
  "notWatching": "文件监听不可用；需要检查",
  "privacy": "索引在本机。使用云端模型时，选中的导航与知识片段会发送给该模型；不等于纯本地隐私模式。",
  "openVault": "打开知识库目录",
  "adjust": "通过 skill 调整配置",
  "setup": "开始初始化问答",
  "selectFolder": "选择文件夹",
  "newPath": "新建或切换知识库",
  "pathPlaceholder": "输入独立的 Vault 绝对路径，或选择文件夹",
  "preview": "预览目录与模板",
  "previewOnly": "以下仅为目录和模板预览，不会写入。真实方案由 research-vault skill 理解项目、问答后单独确认。",
  "skillBound": "绑定入口 /obsidian-setup · research-vault",
  "globalSwitch": "切换将影响全应用后续任务；正在运行的旧任务不会静默写入新库。",
  "selectProject": "请先选择一个项目或打开会话，作为初始化问答的上下文。",
  "pathRequired": "请输入或选择 Vault 路径。",
  "existing": "已有目录",
  "newVault": "尚不存在，将在确认后创建",
  "truncated": "内容已截断，可继续读取",
  "templates": "内置模板预览",
  "library": "共享 Library",
  "projectFolders": "项目目录",
  "legacy": "发现旧项目 Vault 配置（不会覆盖全局绑定）",
  "legacyHint": "请核对后通过初始化流程选择需要的知识库；程序不会自动迁移或删除旧笔记。",
  "notMcp": "原生知识索引，不代表原始 MCP 已连接",
  "empty": "暂无条目",
  "previous": "上一页",
  "next": "下一页",
  "total": "总计",
  "originProject": "候选只在发起项目中审核；已批准的共享 Wiki 可供其他项目检索。",
  "reviewTitle": "审核具体 Wiki 修改",
  "selectReview": "选择一个候选，按需加载差异与来源。",
  "reason": "修改理由",
  "diff": "修改差异",
  "both": "原文 / 拟修改",
  "protected": "受保护的人工内容",
  "before": "修改前托管区",
  "after": "拟替换托管区",
  "sources": "依据与版本",
  "openSource": "读取来源",
  "sourceChanged": "来源已变化或不可读",
  "targetChanged": "目标笔记已变化",
  "expired": "候选或预览已过期",
  "stalePreview": "知识状态已变化，请重新加载预览后审核。",
  "refreshPreview": "重新加载预览",
  "approve": "应用已查看的候选",
  "reject": "拒绝候选",
  "applying": "正在执行…",
  "confirmReview": "我已查看差异和来源，同意应用这一具体修改。",
  "notScience": "通过阅读或发布检查 ≠ 科学结论已验证。批准 Wiki 仅表示接受本次修改。",
  "preserve": "只替换智能体托管区；托管区外的人工正文与批注保持不变。",
  "applied": "Wiki 修改已应用",
  "rejected": "候选已拒绝，笔记未修改",
  "savedPartial": "笔记已保存，但索引或审核记录尚未完成，请查看错误并刷新。",
  "viewNote": "阅读知识条目",
  "openObsidian": "在 Obsidian 中打开",
  "readMore": "继续读取",
  "readBack": "从开头读取",
  "humanReview": "人工复核",
  "missing": "文件不存在或已移除",
  "uiRead": "这里的阅读是供你查看，不计作模型本轮的阅读凭据。",
  "buildIndex": "核对目录 / 重试索引",
  "refreshNavigation": "更新排队中的导航",
  "maintenanceHint": "直接操作后端，不调用模型。目录核对不改写 Wiki 正文；导航更新只处理最多 5 个任务。",
  "confirmNavigation": "确认更新这些导航的智能体托管区？人工内容保留，不会自动综合或改写主题 Wiki。",
  "maintenanceDone": "维护操作已完成",
  "maintenanceBusy": "正在维护，请勿重复提交",
  "problems": "未覆盖或失败的条目（最多显示 20 条）",
  "problemHint": "未索引、不可读和无命中不同。修复文件后可重试索引，不能据此断言库中没有相关知识。",
  "coverageReady": "已完成目录核对",
  "coverageIndexing": "正在建立 / 核对索引",
  "coveragePartial": "索引覆盖不完整",
  "coverageUninitialized": "尚未建立索引",
  "evidenceReview": "待纳入总结的证据",
  "wikiReview": "Wiki 需要复核",
  "navigationJob": "导航待更新",
  "manualReview": "需要阅读资料并提议修改；不会自动消耗模型费用。",
  "flow": "本轮知识访问",
  "details": "查看阅读记录",
  "manage": "管理知识库",
  "resume": "继续完成知识检查",
  "resumeHint": "将向当前模型发送继续处理请求，可能产生模型费用。",
  "navigation": "导航与项目背景",
  "wiki": "相关 Wiki",
  "search": "证据检索",
  "publication": "回答发布检查",
  "notStarted": "尚无完成记录",
  "matched": "返回条目",
  "readScope": "本轮记录的文件与版本",
  "checksNotFacts": "这记录实际步骤，不证明检索充分或结论正确。",
  "preparing": "正在准备知识库导航",
  "navigationPhase": "导航已提供，等待阅读 Wiki",
  "readingWiki": "正在阅读相关 Wiki",
  "searching": "正在检索知识库",
  "readingEvidence": "正在阅读证据",
  "checking": "正在检查引用与版本",
  "released": "发布检查通过",
  "noHits": "本次查询无命中",
  "blocked": "发布被阻塞",
  "unconfigured": "尚未绑定知识库",
  "evidenceOnly": "子智能体材料待主会话核验",
  "interrupted": "本轮已中断",
  "noHitsHint": "无命中只适用于本次查询，不代表整个知识库不存在相关知识。",
  "errorDetails": "查看错误详情",
  "newSetup": "重新配置",
  "notification": "知识库通知"
} as const;
const knowledgeEn: Record<keyof typeof knowledgeZh, string> = {
 "specialists": "Knowledge specialists",
 "specialistMode": "Specialist dispatch mode",
 "specialistAuto": "Automatic by stage",
 "specialistManual": "Explicit delegation only",
 "specialistOff": "Off",
 "specialistCost": "Separate model requests may incur charges. Inherit the parent model unless configured per role. Only the task and selected sources are sent, never parent history.",
 "specialistDenied": "Vault policy denies child access. This switch cannot elevate permissions.",
 "specialistPermissions": "Roles and capability limits",
 "specialistLimits": "Up to 4 calls per turn, 2 knowledge specialists concurrently across the app, 120 seconds each. No shell, network fetch, recursive delegation, live Wiki writes or approval.",
 "specialistModels": "Configure specialist models",
 "specialist_navigator": "Knowledge navigator",
 "specialist_navigator_hint": "Read navigation, locate relevant Wiki and evidence at the start of knowledge tasks.",
 "specialist_evidence": "Evidence curator",
 "specialist_evidence_hint": "Compare assigned sources, versions, applicability and conflicts; no scientific certification.",
 "specialist_wiki": "Wiki editor",
 "specialist_wiki_hint": "Draft after summary save. The host stages the candidate; human approval is still required.",
 "specialist_explainer": "Show Me explainer",
 "specialist_explainer_hint": "Use assigned sources and the loaded skill. The host archives the result; no software execution or tests.",
 "specialistRuns": "Specialist runs",
 "specialistUsage": "Input / output tokens",
 "specialistUnverified": "Specialist summaries are unverified handoffs, not parent read receipts or final conclusions.",
 "worker_queued": "Queued",
 "worker_running": "Running",
 "worker_completed": "Handed off",
 "worker_failed": "Failed",
 "worker_cancelled": "Cancelled",
 "worker_skipped": "Skipped",

 linkPreviewOnly:"Stored note unchanged. Local links resolve to existing files in the matching project:",
 emptyPreview:"No directory entries or path selected. Planned folders and templates remain available below.",
 sampleContent:"Note template content (read-only)",setupComplete:"Setup completed",findings:"Search findings",
 candidateHint:"Search excerpts are not model read receipts or verified scientific conclusions.",outputs:"Outputs and follow-ups",
 noFindings:"No matching items this turn. Indexed sources and synthesized Wiki are separate layers.",
  "title": "Knowledge",
  "subtitle": "Application-wide · project context stays independent",
  "overview": "Overview & setup",
  "reviews": "Wiki review",
  "maintenance": "Index & maintenance",
  "refresh": "Refresh status",
  "loading": "Reading local status…",
  "failed": "Action did not complete",
  "retry": "Retry",
  "close": "Close",
  "notBound": "No shared Vault is bound",
  "notBoundHint": "Create or select once for all projects and new sessions. Code and result directories remain project-local.",
  "disabled": "Application knowledge is disabled in this runtime. Use the updated desktop build.",
  "vault": "Current Vault",
  "scope": "Scope",
  "scopeValue": "All of Percho",
  "project": "Current knowledge project",
  "noProject": "No project selected; shared status only",
  "profile": "Knowledge structure",
  "deposit": "Deposition policy",
  "subagents": "Subagent access",
  "index": "Local index",
  "notes": "Indexed notes",
  "pending": "Pending files",
  "jobs": "Maintenance jobs",
  "lastChecked": "Last inventory check",
  "unknown": "Not completed",
  "watching": "File watcher active",
  "notWatching": "File watcher unavailable; check status",
  "privacy": "The index stays local. When using a cloud model, selected navigation and knowledge excerpts are sent to that model; this is not a fully local privacy mode.",
  "openVault": "Open Vault folder",
  "adjust": "Adjust through the skill",
  "setup": "Start setup interview",
  "selectFolder": "Choose folder",
  "newPath": "Create or switch Vault",
  "pathPlaceholder": "Enter an independent absolute Vault path, or choose a folder",
  "preview": "Preview folders & templates",
  "previewOnly": "This is a read-only directory/template preview. The research-vault skill will inspect context, ask questions and separately confirm the actual plan.",
  "skillBound": "Bound entry /obsidian-setup · research-vault",
  "globalSwitch": "Switching affects subsequent application tasks; an existing task is never silently redirected into the new Vault.",
  "selectProject": "Select a project or open a session as the setup interview context.",
  "pathRequired": "Enter or select a Vault path.",
  "existing": "Existing directory",
  "newVault": "Does not exist; created only after confirmation",
  "truncated": "Content is truncated; continue reading",
  "templates": "Built-in template preview",
  "library": "Shared Library",
  "projectFolders": "Project folders",
  "legacy": "Legacy project Vault found (does not override the global binding)",
  "legacyHint": "Review it and choose through setup; no automatic migration or deletion occurs.",
  "notMcp": "Native knowledge index; not proof of a raw MCP connection",
  "empty": "No items",
  "previous": "Previous",
  "next": "Next",
  "total": "Total",
  "originProject": "Review a candidate in its originating project; approved shared Wiki pages are searchable by other projects.",
  "reviewTitle": "Review this Wiki change",
  "selectReview": "Select a candidate to load its diff and sources on demand.",
  "reason": "Change rationale",
  "diff": "Changes",
  "both": "Before / after",
  "protected": "Protected human content",
  "before": "Previous managed block",
  "after": "Proposed managed block",
  "sources": "Sources & versions",
  "openSource": "Read source",
  "sourceChanged": "Source changed or unreadable",
  "targetChanged": "Target note changed",
  "expired": "Candidate or preview expired",
  "stalePreview": "Knowledge state changed. Reload the preview before applying.",
  "refreshPreview": "Reload preview",
  "approve": "Apply the reviewed candidate",
  "reject": "Reject candidate",
  "applying": "Working…",
  "confirmReview": "I reviewed the changes and sources and approve this exact edit.",
  "notScience": "Read/publication checks do not verify scientific truth. Wiki approval only accepts this edit.",
  "preserve": "Only the managed block is replaced; human text outside it is preserved.",
  "applied": "Wiki change applied",
  "rejected": "Candidate rejected; note unchanged",
  "savedPartial": "The note was saved, but indexing or review recording is incomplete. Check the error and refresh.",
  "viewNote": "Read knowledge note",
  "openObsidian": "Open in Obsidian",
  "readMore": "Continue reading",
  "readBack": "Read from start",
  "humanReview": "Human review",
  "missing": "File is missing or removed",
  "uiRead": "This human-facing read does not grant the model a read receipt.",
  "buildIndex": "Check inventory / retry index",
  "refreshNavigation": "Refresh queued navigation",
  "maintenanceHint": "Calls the backend directly, not a model. Inventory checks do not rewrite Wiki; navigation updates handle at most 5 jobs.",
  "confirmNavigation": "Update managed navigation blocks? Human content is preserved; topic Wiki is not synthesized or rewritten.",
  "maintenanceDone": "Maintenance completed",
  "maintenanceBusy": "Maintenance is running; please do not submit twice",
  "problems": "Unindexed or failed items (up to 20 shown)",
  "problemHint": "Unindexed, unreadable and zero hits are different outcomes. Repair files and retry; do not infer absence.",
  "coverageReady": "Inventory check complete",
  "coverageIndexing": "Building / reconciling index",
  "coveragePartial": "Incomplete index coverage",
  "coverageUninitialized": "Index not initialized",
  "evidenceReview": "Evidence awaiting synthesis",
  "wikiReview": "Wiki requires review",
  "navigationJob": "Navigation update pending",
  "manualReview": "Read the material and propose a reviewed change; no automatic model spend.",
  "flow": "This turn’s knowledge access",
  "details": "Reading records",
  "manage": "Manage knowledge",
  "resume": "Continue knowledge checks",
  "resumeHint": "Sends a continuation request to the selected model; model charges may apply.",
  "navigation": "Navigation & project context",
  "wiki": "Relevant Wiki",
  "search": "Evidence search",
  "publication": "Publication check",
  "notStarted": "No completion recorded",
  "matched": "Returned items",
  "readScope": "Files and versions recorded this turn",
  "checksNotFacts": "These are observable steps, not proof of complete retrieval or correct conclusions.",
  "preparing": "Preparing knowledge navigation",
  "navigationPhase": "Navigation supplied; waiting for Wiki reads",
  "readingWiki": "Reading related Wiki",
  "searching": "Searching knowledge",
  "readingEvidence": "Reading evidence",
  "checking": "Checking citations and versions",
  "released": "Publication check passed",
  "noHits": "No hits for this query",
  "blocked": "Publication blocked",
  "unconfigured": "No Vault bound",
  "evidenceOnly": "Subagent evidence awaits verification",
  "interrupted": "Turn interrupted",
  "noHitsHint": "Zero hits apply only to this query, not to the whole Vault.",
  "errorDetails": "Error details",
  "newSetup": "Configure again",
  "notification": "Knowledge notice"
};
export function useKnowledgeText() { const language=useI18nStore(s=>s.language); const dictionary=language==='zh'?knowledgeZh:knowledgeEn; return (key:keyof typeof knowledgeZh)=>dictionary[key]; }
